WIP: Chef 16 Fixes
osuosl-cookbooks/osl-jenkins pull request #197
Opened 2020-10-01 22:02 UTC by daviddjh

2020-10-01 22:05 UTC, daviddjh commented
Many of the suites require multiple converges. packer-pipeline-node-centos-7 has issues with the dogpile python module.

2020-10-03 00:07 UTC, ramereth commented
@daviddjh was the jenkins upgrade a requirement?

2020-10-06 21:32 UTC, daviddjh commented
> @daviddjh was the jenkins upgrade a requirement?

@ramereth Yes, I believe It was DNF on centos 8 that couldn't find version 2.235.3-1.1

2020-10-07 17:45 UTC, ramereth commented
@daviddjh strange that wasn't caught when we added EL8.

2020-10-07 20:12 UTC, ramereth requested changes
Please update the stubs like the following:
```diff
diff --git a/spec/spec_helper.rb b/spec/spec_helper.rb
index 36d6227..0f32ca6 100644
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -22,11 +22,7 @@ shared_context 'common_stubs' do
                    'Not Found',
                    Net::HTTPResponse.new('1.1', '404', '')
                  ))
-    stub_command("chef gem list -i -v '< 2.0.0' netaddr").and_return(true)
-    stub_command("chef gem list -i -v '< 4.0.0' kitchen-terraform").and_return(true)
-    stub_command("chef gem list -i -v '>= 2.0.0' netaddr").and_return(false)
-    stub_command('chef gem list -i kitchen-transport-rsync').and_return(false)
-    stub_command("chef gem list -i -v '= 2.7.5' rubygems")
+    stub_command("/opt/cinc-workstation/embedded/bin/gem list -i -v '< 1.1.0.rc1' bcrypt_pbkdf")
     stub_command('/opt/os-client/bin/pip freeze | grep -q python-openstackclient==3.14.3')
   end
 end
```
In addition, don't forget to update the ChefSpec tests for the changes you made.

I'm still looking at the other issues.

2020-10-07 21:24 UTC, ramereth commented
Some other comments:
- Please fix the InSpec test for the `chef-ci-cookbook-template` suite.
- The multi-converge on some suites are a known problem that we need to figure out later unfortunately. It might be good to add comments on suites that require that

I'm still looking at the other suites...

2020-10-07 23:06 UTC, ramereth commented
>  packer-pipeline-node-centos-7 has issues with the dogpile python module.

I've narrowed down the problem with this suite. I'm going to be making a PR in base which resolves it.

2020-10-13 23:17 UTC, ramereth commented on recipes/plugins.rb
>  end
I think you want to remove the `log` resource and move the `only_if` to the `notify_group` resource.

2020-10-22 01:31 UTC, daviddjh commented
The latest log resource commit hasn't been verified in kitchen. Chef began complaining about java cookbook resource deprecations.

2020-10-22 23:32 UTC, ramereth approved these changes
Please do a minor bump.

2020-10-23 17:54 UTC, daviddjh commented
!bump minor *

2020-10-23 17:54 UTC, merged

2020-10-23 17:54 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.9.0.  Have a nice day!