Initial removal of manage_by_attributes
osuosl-cookbooks/osl-jenkins pull request #215
Opened 2022-07-15 16:23 UTC by pasimko

Did not see any tests that needed changing

2022-07-18 19:04 UTC, ramereth requested changes

2022-07-21 23:29 UTC, ramereth commented on spec/unit/recipes/packer_pipeline_node_spec.rb
> +      #  )
Please go ahead and remove this.

2022-07-21 23:29 UTC, ramereth commented on test/integration/packer_pipeline_node/inspec/packer_pipeline_node_spec.rb
> +# end
Please just remove this (and above) instead of commenting it out.

2022-07-22 20:58 UTC, ramereth commented
!bump patch ~

2022-07-22 20:58 UTC, merged

2022-07-22 20:58 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.16.1.  Have a nice day!